### ISSUE TITLE
Cannot load custom http-server plugin

### ISSUE THREAD

**Issue by laacz** [krakend/krakend-ce#765]
**Environment info:**

* KrakenD version: 2.3.3-ee
* System info: `docker`
* Hardware specs: irrelevant
* Backend technology: irrelevant
* Additional environment information: Run via official image `krakend/krakend-ee:2.3.3-watch`

**Describe the bug**
Trying to build a plugin [from the documentation](https://www.krakend.io/docs/extending/http-server-plugins/) gives an error, when deployed to krakend:

```
krakend-krakend-1  | [00] 2023/08/01 11:22:42 KRAKEND DEBUG: [SERVICE: Plugin Loader] Starting loading process
krakend-krakend-1  | [00] 2023/08/01 11:22:42 KRAKEND DEBUG: [SERVICE: Executor Plugin] plugin #0 (plugins/api-keys.so): plugin.Open("plugins/api-keys"): plugin was built with a different version of package runtime
krakend-krakend-1  | [00] 2023/08/01 11:22:42 KRAKEND DEBUG: [SERVICE: Handler Plugin] plugin #0 (plugins/api-keys.so): plugin.Open("plugins/api-keys.so"): plugin was built with a different version of package runtime (previous failure)
krakend-krakend-1  | [00] 2023/08/01 11:22:42 KRAKEND DEBUG: [SERVICE: Modifier Plugin] plugin #0 (plugins/api-keys.so): plugin.Open("plugins/api-keys.so"): plugin was built with a different version of package runtime (previous failure)
krakend-krakend-1  | [00] 2023/08/01 11:22:42 KRAKEND DEBUG: [SERVICE: Plugin Loader] Loading process completed
```

Plugin is being built with `docker run -it -v "$PWD:/app" -w /app krakend/builder:2.3.3 go -v build -buildmode=plugin -o api-keys.so .`. 

It appears that there are some environmental differences between kakend/krakend-ee:2.3.3 and krakend/builder:2.3.3:

```bash
# krakend, go and glibc version
docker exec -it krakend-krakend-1 krakend version
KrakenD Version: 2.3.3-ee
Go Version: 1.20.6
Glibc Version: MUSL-1.2.4_(alpine-3.18.2)

# builder go and glibc version
docker run -it -v "$PWD:/app" -w /app krakend/builder:2.3.3 sh -c 'go version && ldd'
go version go1.20.4 linux/amd64
musl libc (x86_64)
Version 1.2.4
```

**Your configuration file**:

```json
{
    "$schema": "https://www.krakend.io/schema/v3.json",
    "version": 3,
    "plugin": {
        "pattern": ".so",
        "folder": "./plugins"
    },
    "extra_config": {
        "plugin/http-server": {
            "name": [
                "api-keys"
            ],
            "krakend-server-example": {
                "path": "/*"
            }
        }
    },
    "endpoints": [
        {
            "endpoint": "/anything",
            "backend": [
                {
                    "url_pattern": "/anything",
                    "host": [
                        "http://httpbin/"
                    ]
                }
            ]
        }
    ]
}
```

**Commands used**

```bash
# Starting krakend
docker compose up
```

Docker compose:

```yml
version: '3.3'
services:
  krakend:
  # :watch image is used in development mode
  # :2.4.2 (or any other version) image is used in production mode
    image: krakend/krakend-ee:2.3.3-watch
    environment:
      # enable flexible configuration
      - FC_ENABLE=1
      - FC_TEMPLATES=/etc/krakend/
      - KRAKEND_LOGGING_LEVEL=INFO
      - FC_OUT=/etc/krakend/krakend.json
    volumes:
      - ./krakend:/etc/krakend/
    ports:
      - 8080:8080
    command: ["run", "-d", "-c", "krakend-flexible-config.tmpl"]
    networks:
      - krakend
  httpbin:
    image: kennethreitz/httpbin
    ports:
      - 8081:80
    networks:
      - krakend
networks:
  krakend:
```

**Expected behavior**
Plugin to be run.

**Logs**
See above.
