### ISSUE TITLE
Docker & traefik = connect: connection refused

### ISSUE THREAD

**Issue by ozee31** [krakend/krakend-ce#768]
**Describe what are you trying to do**:
I'm trying to configure an entry point to call a backend. I use traefik with traefik.me

**Your configuration file**:

```json
{
  "$schema": "https://www.krakend.io/schema/v3.json",
  "version": 3,
  "name": "Obat - KrakenD - API Gateway",
  "timeout": "10000ms",
  "cache_ttl": "300s",
  "output_encoding": "json",
  "port": 8080,
  "debug_endpoint": true,
  "echo_endpoint": true,
  "host": ["https://krakend-obat.traefik.me"],
  "endpoints": [
    {
      "endpoint": "/v1/worksites/{worksiteId}/working-times",
      "method": "GET",
      "backend": [
        {
          "url_pattern": "/v1/worksites/{worksiteId}/working-times",
          "method": "GET",
          "host": ["https://obat-timetracker.traefik.me"]
        }
      ]
    }
  ]
}
```

docker-compose config for krakend

```yml
version: "3.9"

services:
  krakend:
    image: devopsfaith/krakend:latest
    # ports:
    #   - 9999:9999
    expose:
      - 8080
    labels:
      - "traefik.docker.network=traefik"
      - "traefik.enable=true"
      - "traefik.http.routers.krakend.tls=true"
      - "traefik.http.routers.krakend.entrypoints=web,websecure"
      - "traefik.http.routers.krakend.rule=Host(`krakend-obat.traefik.me`)"
    networks:
      - traefik
    volumes:
      - ./src:/etc/krakend

networks:
  traefik:
    name: traefik
    external: true
```

docker-compose config for my obat-timetracker service

```yml
---
version: "3.9"

x-default-component: &default-component
  networks:
    - obat_db
  deploy:
    restart_policy:
      condition: on-failure

services:
  mariadb:
    <<: *default-component
    container_name: timetracker_db
    image: mariadb:10.3
    expose:
      - 3309
    ports:
      - "3309:3306"
    volumes:
      - timetracker_db:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: password
      MARIADB_USER: user
      MARIADB_DATABASE: obat_timetracker
      MARIADB_PASSWORD: password

  mariadb-test:
    <<: *default-component
    container_name: timetracker_db_test
    image: mariadb:10.3
    expose:
      - 3310
    ports:
      - "3310:3306"
    volumes:
      - ./data/db:/tmp/obat
      - timetracker_db_test:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: password
      MARIADB_USER: user
      MARIADB_DATABASE: obat_timetracker_test
      MARIADB_PASSWORD: password_test

  timetracker_app:
    <<: *default-component
    container_name: timetracker_app
    image: registry.gitlab.com/obatfr/container/php/php81-development:1.0.0
    restart: unless-stopped
    volumes:
      - ${PWD}:/app

  timetracker_web:
    <<: *default-component
    container_name: timetracker_web
    image: registry.gitlab.com/obatfr/container/nginx/nginx-development:1.0.0
    restart: unless-stopped
    environment:
      PHP_FPM_HOST: timetracker_app
    volumes:
      - ${PWD}/public:/app/public
    labels:
      - "traefik.docker.network=traefik"
      - "traefik.enable=true"
      - "traefik.http.services.timetracker_web.loadbalancer.server.port=8080"
      - "traefik.http.routers.timetracker_web.tls=true"
      - "traefik.http.routers.timetracker_web.entrypoints=web,websecure"
      - "traefik.http.routers.timetracker_web.rule=Host(`obat-timetracker.traefik.me`)"
    depends_on:
      timetracker_app:
        condition: service_healthy
    networks:
      - traefik
      - obat_db

volumes:
  timetracker_db:
    name: timetracker_db
  timetracker_db_test:
    name: timetracker_db_test

networks:
  obat_db:
    name: obat_db
  traefik:
    name: traefik
    external: true
```

When try to ping my service inside of krakend

```
docker-compose exec krakend ping obat-timetracker.traefik.me

PING obat-timetracker.traefik.me (127.0.0.1): 56 data bytes
64 bytes from 127.0.0.1: seq=0 ttl=64 time=0.023 ms
64 bytes from 127.0.0.1: seq=1 ttl=64 time=0.112 ms
```

but when call in http `https://krakend-obat.traefik.me/v1/worksites/634040be09806/working-times` i have an 500 error and logs are

```
krakend_1  | 2023/08/07 15:21:29 KRAKEND ERROR: [ENDPOINT: /v1/worksites/:worksiteId/working-times] Get "https://obat-timetracker.traefik.me/v1/worksites/634040be09806/working-times": dial tcp 127.0.0.1:443: connect: connection refused
krakend_1  | [GIN] 2023/08/07 - 15:21:29 | 500 |    5.039641ms |      172.19.0.1 | GET      "/v1/worksites/634040be09806/working-times"
krakend_1  | Error #01: Get "https://obat-timetracker.traefik.me/v1/worksites/634040be09806/working-times": dial tcp 127.0.0.1:443: connect: connection refused
```

I have the same problem if a use localhost for backend

```json
{
      "endpoint": "/v1/worksites/{worksiteId}/working-times",
      "method": "GET",
      "backend": [
        {
          "url_pattern": "/v1/worksites/{worksiteId}/working-times",
          "method": "GET",
          "host": ["http://localhost:8083"]
        }
      ]
    }
```
