### ISSUE TITLE
HEAD method is not supported

### ISSUE THREAD

**Issue by digitive** [krakend/krakend-ce#846]
**Environment info:**

* KrakenD version: Run `krakend help | grep Version` and copy the output here

```
❯ krakend -h | grep Version
Version: 2.5.1
```

**Describe the bug**
The http HEAD method is not supported. While evaluating Krakend to proxy HEAD request to upstream, Krakend doesn't work.

**Your configuration file**:

```yaml
$schema: "https://www.krakend.io/schema/v2.5/krakend.json"
version: 3
port: 8280
endpoints:
  - endpoint: /api/.well-known/testservice
    method: HEAD
    backend:
      - url_pattern: /.well-known/testservice
        method: HEAD
        host:
          - http://localhost:3000
```

**Commands used**
How did you start the software?
```bash
krakend run -c krakend.yml
```

Then test with curl
```bash
> curl -X HEAD -i http://localhost:8280/api/.well-known/jmap\?noRedirect
Warning: Setting custom HTTP method to HEAD with -X/--request may not work the
Warning: way you want. Consider using -I/--head instead.
HTTP/1.1 404 Not Found
Content-Type: text/plain
X-Krakend: Version 2.5.1
X-Krakend-Completed: false
Date: Fri, 16 Feb 2024 07:18:18 GMT
Content-Length: 18
```

**Expected behavior**
Krakend forward request to upstream server and forward back response header from upstream server, especially the `Location` header.
According to https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods
The HEAD method asks for a response identical to a GET request, but without the response body.

```
❯ curl -X HEAD -i http://localhost:3000/.well-known/testserver\?noRedirect
Warning: Setting custom HTTP method to HEAD with -X/--request may not work the
Warning: way you want. Consider using -I/--head instead.
HTTP/1.1 200 OK
Access-Control-Expose-Headers: Location
Location: http://localhost:3000/auth
Vary: Origin
Date: Fri, 16 Feb 2024 07:17:34 GMT
Connection: close
```

**Logs**
```bash
2024/02/16 17:16:58 KRAKEND ERROR: [SERVICE: Gin] [ENDPOINT: /api/.well-known/jmap ] Unsupported method HEAD
```
