### ISSUE TITLE
Logs not working on Open Telemetry Integration

### ISSUE THREAD

**Issue by tfsantosbr** [krakend/krakend-ce#966]
**Environment info:**

* KrakenD version: v2.9.1
* System info: MINGW64_NT-10.0-26100 3.4.7-ea781829.x86_64 x86_64
* Hardware specs: Ryzen 7 5800X, 16GB RAM
* Backend technology: C#
* Additional environment information: Docker Compose

**Describe the bug**
I'm trying to use Krakend with Open Telemetry for monitoring, tracing and metrics are good, but logs not working.
I'm using otel-collector + grafana + loki + tempo + prometheus on observability.
I'm using docker-compose to run the solution

**Your configuration file**:
krakend.json file:
```json
{
  "$schema": "https://www.krakend.io/schema/v2.8/krakend.json",
  "version": 3,
  "timeout": "2s",
  "output_encoding": "no-op",
  "endpoints": [
    {
      "endpoint": "/orders/v1/orders",
      "method": "GET",
      "backend": [
        {
          "url_pattern": "/orders",
          "method": "GET",
          "host": ["http://orders-api:8080"]
        }
      ]
    },
    {
      "endpoint": "/orders/v1/orders/{id}",
      "method": "GET",
      "backend": [
        {
          "url_pattern": "/orders/{id}",
          "method": "GET",
          "host": ["http://orders-api:8080"]
        }
      ]
    },
    {
      "endpoint": "/orders/v1/orders",
      "method": "POST",
      "backend": [
        {
          "url_pattern": "/orders",
          "method": "POST",
          "host": ["http://orders-api:8080"]
        }
      ],
      "extra_config": {
        "auth/validator": {
          "alg": "RS256",
          "jwk_url": "http://keycloak:8080/realms/eventflix/protocol/openid-connect/certs",
          "disable_jwk_security": true,
          "operation_debug": true,
          "roles_key": "realm_access.roles",
          "roles_key_is_nested": true,
          "roles": ["admin"]
        }
      }
    },
    {
      "endpoint": "/orders/v1/orders/{id}",
      "method": "PUT",
      "backend": [
        {
          "url_pattern": "/orders/{id}",
          "method": "PUT",
          "host": ["http://orders-api:8080"]
        }
      ]
    },
    {
      "endpoint": "/orders/v1/orders/{id}",
      "method": "DELETE",
      "backend": [
        {
          "url_pattern": "/orders/{id}",
          "method": "DELETE",
          "host": ["http://orders-api:8080"]
        }
      ]
    },
    {
      "endpoint": "/products/v1/products",
      "method": "GET",
      "backend": [
        {
          "url_pattern": "/products",
          "method": "GET",
          "host": ["http://products-api:8080"]
        }
      ]
    },
    {
      "endpoint": "/products/v1/products/{id}",
      "method": "GET",
      "backend": [
        {
          "url_pattern": "/products/{id}",
          "method": "GET",
          "host": ["http://products-api:8080"]
        }
      ]
    },
    {
      "endpoint": "/products/v1/products",
      "method": "POST",
      "backend": [
        {
          "url_pattern": "/products",
          "method": "POST",
          "host": ["http://products-api:8080"]
        }
      ]
    },
    {
      "endpoint": "/products/v1/products/{id}",
      "method": "PUT",
      "backend": [
        {
          "url_pattern": "/products/{id}",
          "method": "PUT",
          "host": ["http://products-api:8080"]
        }
      ]
    },
    {
      "endpoint": "/products/v1/products/{id}",
      "method": "DELETE",
      "backend": [
        {
          "url_pattern": "/products/{id}",
          "method": "DELETE",
          "host": ["http://products-api:8080"]
        }
      ]
    },
    {
      "endpoint": "/products/v1/categories",
      "method": "GET",
      "backend": [
        {
          "url_pattern": "/products/categories",
          "method": "GET",
          "host": ["http://products-api:8080"]
        }
      ]
    }
  ],
  "extra_config": {
    "telemetry/opentelemetry": {
      "service_name": "krakend-api-gateway",
      "service_version": "1.0.0",
      "exporters": {
        "otlp": [
          {
            "name": "local-otlp-collector",
            "host": "otel-collector",
            "port": 4317,
            "use_http": false
          }
        ]
      },
      "layers": {
        "backend": {
          "metrics": {
            "round_trip": true,
            "read_payload": true,
            "detailed_connection": true
          },
          "traces": {
            "round_trip": true,
            "read_payload": true,
            "detailed_connection": true
          }
        }
      }
    },
    "telemetry/logging": {
      "level": "INFO",
      "prefix": "[KRAKEND]",
      "syslog": false,
      "stdout": true
    },
    "telemetry/logstash": {
      "enabled": true
    }
  }
}

```

docker-compose.yml file:
```yml
services:
  orders-api:
    build:
      context: ./src/Orders.API
      dockerfile: Dockerfile
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - api-gateway-net

  products-api:
    build:
      context: ./src/Products.API
      dockerfile: Dockerfile
    ports:
      - "6000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - api-gateway-net

  keycloak:
    image: quay.io/keycloak/keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_LOG_LEVEL: INFO
      KC_HEALTH_ENABLED: true
    volumes:
      - ./config/keycloak/realm.json:/opt/keycloak/data/import/realm-export.json:ro
    ports:
      - "7000:8080"
    command:
      - start-dev
      - --import-realm
    networks:
      - api-gateway-net

  krakend:
    image: devopsfaith/krakend:watch
    volumes:
      - ./config/krakend:/etc/krakend:ro
    ports:
      - "1234:1234"
      - "8080:8080"
      - "8090:8090"
    command: ["run", "-c", "/etc/krakend/krakend.json", "-d"]
    networks:
      - api-gateway-net

  # OBSERVABILITY ---

  otel-collector:
    image: otel/opentelemetry-collector-contrib
    volumes:
      - ./config/otel-collector/otel-collector.yaml:/etc/otelcol-contrib/config.yaml
    ports:
      - 8888:8888 # Prometheus metrics exposed by the Collector
      - 8889:8889 # Prometheus exporter metrics
      - 13133:13133 # health_check extension
      - 4317:4317 # OTLP gRPC receiver
      - 4318:4318 # OTLP http receiver
    networks:
      - api-gateway-net

  prometheus:
    image: prom/prometheus
    volumes:
      - ./config/prometheus/:/etc/prometheus/
      - prometheus-storage:/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --web.enable-remote-write-receiver
      - --enable-feature=exemplar-storage
      - --enable-feature=native-histograms
    ports:
      - 9090:9090
    networks:
      - api-gateway-net

  grafana:
    image: grafana/grafana
    volumes:
      - ./config/grafana/provisioning/:/etc/grafana/provisioning/
      - grafana-storage:/var/lib/grafana
    environment:
      GF_SECURITY_ADMIN_PASSWORD: "admin"
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    networks:
      - api-gateway-net

  loki:
    image: grafana/loki:latest
    command: -config.file=/etc/loki/loki-config.yaml
    volumes:
      - ./config/loki/loki-config.yaml:/etc/loki/loki-config.yaml
    ports:
      - "3100:3100"
    networks:
      - api-gateway-net

  tempo:
    image: grafana/tempo:latest
    command: -config.file=/etc/tempo.yaml
    volumes:
      - ./config/tempo/tempo.yaml:/etc/tempo.yaml
    ports:
      - "3200:3200" # tempo
      - "4317" # otlp grpc
    networks:
      - api-gateway-net

volumes:
  grafana-storage:
    name: mc-grafana-storage
  prometheus-storage:
    name: mc-prometheus-storage

networks:
  api-gateway-net:
    driver: bridge
```

**Commands used**
How did you start the software?
```
docker-compose up --build
```
**Expected behavior**
Logs must be in Grafana Logs Explorer, I can see logs from another services, like my APIs, but nor from Krakend.

**Logs**

**Additional context**
